# Generated by Django 5.1.2 on 2024-11-27 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_name', models.CharField(max_length=100)),
                ('prod_price', models.IntegerField()),
                ('prod_category', models.CharField(max_length=100)),
                ('prod_qty', models.IntegerField()),
                ('prod_img', models.ImageField(upload_to='products/')),
                ('prod_desc', models.CharField(max_length=100)),
            ],
        ),
    ]
