# Generated by Django 5.1.2 on 2025-05-15 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_users'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
